### ISSUE TITLE
Extension of DockerfilePaser object to support multi-stage builds

### ISSUE THREAD

**Issue by peterkline** [DBuildService/dockerfile-parse#53]
This request is more to extend for what my needs are based on currently latest release.

1. Type: list 
   Name: 'baseimages' 
   Purpose: User could do a iterate through the base images 
2. Type: boolean
    Name: multistage
    Purpose: User can easily check if docker file is indeed a multistage.  Obviously a user could do the same check with a len on the baseimages but this would be a simple shortcut.

**Comment by lcarva** [comment]
I think we also need to consider the instructions on each stage. For instance, the ability to add a LABEL on the first stage.

Maybe the concept of `stage_context` needs to be introduced. This could be used when modifying instructions. By default, it's the last context which is essentially what we have today.

For reading though, we need to take into account instructions from previous stages as well. For instance an ENV defined in first stage, is available in second stage. I believe this is true for every instruction except for FROM.

**Comment by peterkline** [comment]
If everything is a pass-through except the FROM and to preserve the integrity maybe there could be a list of Parser objects created/added.  This would mean that existing implementation is saved but an advanced call could be made that would allow a user to iterate through the objects?  This would mean that if multi-stage is extended by Docker, then whatever isn't a pass-through (like FROM) would be overwritten or removed in additonal/new/removed strings/bools/etc?

**Comment by sosiouxme** [comment]
Since I've been working on multistage builds design, this is very apropos.

I don't think any instructions do apply to later stages. See for instance for ENV: ["This value will be in the environment for all subsequent instructions in the build stage"](https://docs.docker.com/engine/reference/builder/#env) implies not in future stages. This is what I would expect. The ARG instruction doc is [more explicit about the same](https://docs.docker.com/engine/reference/builder/#scope). LABEL docs don't say but as they are inherited from the base image I would assume they also apply only for the current stage. I can do a little testing in a bit to ensure this is true.

It bears thinking about how detailed multistage support should be. If you're parsing a Dockerfile, it's probably in the hopes of using it in an automated build. Intermediate stages are not generally interesting in and of themselves -- there isn't even a mechanism for tagging them (other than running docker tag manually based on the hash). You would probably not be interested in labeling them, and I'm not even sure about setting ENVs. The final stage is the main concern, and it would likely be simplest if, when there were multiple stages, labels and envs and baseimage referred only to that.

Having a stage context to pick which stage you're talking about, or supplying a list of parsed stages that can be manipulated individually would be nice, but how necessary is it?

**Comment by sosiouxme** [comment]
Regardless of the previous comment, some accommodation is necessary for the `FROM ... AS ...` format. I was thinking that to enable manipulating the FROM in each stage I would actually add a `Froms` class similar to `Envs` and `Labels` (and an attribute to retrieve a collection of them).

**Comment by twaugh** [comment]
Support for multi-stage builds was added #58.
